FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

COPY . .

RUN npx prisma generate
RUN npm run build


FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache dumb-init netcat-openbsd

RUN addgroup -S nodejs && adduser -S nestjs

COPY --from=builder --chown=nestjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nestjs:nodejs /app/dist ./dist
COPY --from=builder --chown=nestjs:nodejs /app/prisma ./prisma
COPY --from=builder --chown=nestjs:nodejs /app/package*.json ./
COPY --chown=nestjs:nodejs entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# Garantizar permisos de escritura para el usuario nestjs
RUN chown -R nestjs:nodejs /app && chmod -R 755 /app

USER nestjs
EXPOSE 3000
ENTRYPOINT ["dumb-init", "/usr/local/bin/entrypoint.sh"]